services:
  postgres:
    image: postgres:latest
    container_name: devfinance-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=devfinance
    volumes:
      - pg_data:/var/lib/postgresql/data
  pgadmin4:
    image: elestio/pgadmin:latest
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=tiagoltavares2002@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=senha123
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pg_data:
